apiVersion: v1
kind: Service
metadata:
  name: intecapp
spec:
  type: NodePort
  selector:
    universidad: intec
    edificio: gc
    componente: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
