apiVersion: v1
kind: Service
metadata:
  name: blackfriday-ofertas
spec:
  type: NodePort
  selector:
    departamento: mercadeo
    app: blackfriday-ofertas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
