apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-cred
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  MONGO_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
  MONGO_DB: {{ .Values.mongodb.auth.database | quote }}

